In [3]:
import numpy as np

In [4]:
data=np.random.rand(5)*100

In [5]:
data

array([58.45909536, 60.61411339, 58.53844168,  4.28330766, 12.66433682])

In [6]:
def MinMaxNormalizyonu(data):
    minVeri=np.min(data)
    maxVeri=np.max(data)
    sonuc=(data-minVeri) /(maxVeri-minVeri)
    return sonuc

In [7]:
normalizeEdilmişData=MinMaxNormalizyonu(data)
print("Normalizasyon öncesi:", data)
print("*************************************************************")
print("Normalizasyon sonrası:", normalizeEdilmişData)

Normalizasyon öncesi: [58.45909536 60.61411339 58.53844168  4.28330766 12.66433682]
*************************************************************
Normalizasyon sonrası: [0.96174353 1.         0.9631521  0.         0.14878234]


In [8]:
def İstatistikselNormalizasyon(data):
    ortalama=np.mean(data)
    standartSapma=np.std(data)
    sonuc=(data-ortalama) / (standartSapma)
    return sonuc

In [9]:
normalizeEdilmişData2=İstatistikselNormalizasyon(data)
print("Normalizasyon öncesi:", data)
print("*************************************************************")
print("Normalizasyon sonrası:", normalizeEdilmişData2)

Normalizasyon öncesi: [58.45909536 60.61411339 58.53844168  4.28330766 12.66433682]
*************************************************************
Normalizasyon sonrası: [ 0.78172012  0.86790217  0.78489328 -1.38484207 -1.0496735 ]


In [10]:
def logaritmikNormalizasyon(data):
    return np.log(data)

In [11]:
normalizeEdilmişData3=logaritmikNormalizasyon(data)
print("Normalizasyon öncesi:", data)
print("*************************************************************")
print("Normalizasyon sonrası:", normalizeEdilmişData3)

Normalizasyon öncesi: [58.45909536 60.61411339 58.53844168  4.28330766 12.66433682]
*************************************************************
Normalizasyon sonrası: [4.06832729 4.10452776 4.06968366 1.45472553 2.53878992]


In [12]:
def KarakokNormalizasyonu(data):
    return np.sqrt(data)

In [13]:
normalizeEdilmişData4=KarakokNormalizasyonu(data)
print("Normalizasyon öncesi:", data)
print("*************************************************************")
print("Normalizasyon sonrası:", normalizeEdilmişData4)

Normalizasyon öncesi: [58.45909536 60.61411339 58.53844168  4.28330766 12.66433682]
*************************************************************
Normalizasyon sonrası: [7.64585478 7.78550662 7.65104187 2.06961534 3.55869875]


In [15]:
print("Normalizasyon öncesi:", data)
print("*************************************************************")

print("Min Max Normalizasyon sonrası:", normalizeEdilmişData)
print("*************************************************************")

print("İstatistiksel Normalizasyon sonrası:", normalizeEdilmişData2)
print("*************************************************************")

print("Logaritmik Normalizasyon sonrası:", normalizeEdilmişData3)
print("*************************************************************")

print("Karakök Normalizasyon sonrası:", normalizeEdilmişData4)

Normalizasyon öncesi: [58.45909536 60.61411339 58.53844168  4.28330766 12.66433682]
*************************************************************
Min Max Normalizasyon sonrası: [0.96174353 1.         0.9631521  0.         0.14878234]
*************************************************************
İstatistiksel Normalizasyon sonrası: [ 0.78172012  0.86790217  0.78489328 -1.38484207 -1.0496735 ]
*************************************************************
Logaritmik Normalizasyon sonrası: [4.06832729 4.10452776 4.06968366 1.45472553 2.53878992]
*************************************************************
Karakök Normalizasyon sonrası: [7.64585478 7.78550662 7.65104187 2.06961534 3.55869875]


In [16]:
from sklearn.preprocessing import StandardScaler

In [19]:
data=data.reshape(-1,1)

In [20]:
sc = StandardScaler()

In [21]:
print(sc.fit(data))

StandardScaler()


In [22]:
data

array([[58.45909536],
       [60.61411339],
       [58.53844168],
       [ 4.28330766],
       [12.66433682]])

In [24]:
scNormalizasyon= sc.transform(data)

In [25]:
print("Normalizasyon öncesi:", data)
print("*************************************************************")
print("Normalizasyon sonrası:",scNormalizasyon)

Normalizasyon öncesi: [[58.45909536]
 [60.61411339]
 [58.53844168]
 [ 4.28330766]
 [12.66433682]]
*************************************************************
Normalizasyon sonrası: [[ 0.78172012]
 [ 0.86790217]
 [ 0.78489328]
 [-1.38484207]
 [-1.0496735 ]]


In [26]:
print("Normalizasyon sonrası:", normalizeEdilmişData2)

Normalizasyon sonrası: [ 0.78172012  0.86790217  0.78489328 -1.38484207 -1.0496735 ]


In [49]:
import pandas as pd

In [50]:
iris=pd.read_csv("iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [51]:
iris.drop(["Id"],axis=1,inplace=True)

In [52]:
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [53]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
scaler.fit_transform(iris)

ValueError: could not convert string to float: 'Iris-setosa'

In [54]:
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [55]:
iris.Species.value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64

In [56]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
iris.Species=le.fit_transform(iris.Species)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [57]:
iris.Species.unique()

array([0, 1, 2], dtype=int64)

In [58]:
iris.Species.value_counts()

2    50
1    50
0    50
Name: Species, dtype: int64

In [60]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
data2 = scaler.fit_transform(iris)
print(data2)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00
  -1.22474487e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00
  -1.22474487e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00
  -1.22474487e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00
  -1.22474487e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00
  -1.22474487e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00

In [62]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
data=iris.values[:,:]
data = scaler.fit_transform(data)
data2 = pd.DataFrame(data)
data2.head(25)

0         1         2         3         4
0  -0.900681  1.032057 -1.341272 -1.312977 -1.224745
1  -1.143017 -0.124958 -1.341272 -1.312977 -1.224745
2  -1.385353  0.337848 -1.398138 -1.312977 -1.224745
3  -1.506521  0.106445 -1.284407 -1.312977 -1.224745
4  -1.021849  1.263460 -1.341272 -1.312977 -1.224745
5  -0.537178  1.957669 -1.170675 -1.050031 -1.224745
6  -1.506521  0.800654 -1.341272 -1.181504 -1.224745
7  -1.021849  0.800654 -1.284407 -1.312977 -1.224745
8  -1.748856 -0.356361 -1.341272 -1.312977 -1.224745
9  -1.143017  0.106445 -1.284407 -1.444450 -1.224745
10 -0.537178  1.494863 -1.284407 -1.312977 -1.224745
11 -1.264185  0.800654 -1.227541 -1.312977 -1.224745
12 -1.264185 -0.124958 -1.341272 -1.444450 -1.224745
13 -1.870024 -0.124958 -1.511870 -1.444450 -1.224745
14 -0.052506  2.189072 -1.455004 -1.312977 -1.224745
15 -0.173674  3.114684 -1.284407 -1.050031 -1.224745
16 -0.537178  1.957669 -1.398138 -1.050031 -1.224745
17 -0.900681  1.032057 -1.341272 -1.181504 -1.224745
18 -0.173674  1.726266 -1.170675 -1.181504 -1.224745
19 -0.900681  1.726266 -1.284407 -1.181504 -1.224745
20 -0.537178  0.800654 -1.170675 -1.312977 -1.224745
21 -0.900681  1.494863 -1.284407 -1.050031 -1.224745
22 -1.506521  1.263460 -1.568735 -1.312977 -1.224745
23 -0.900681  0.569251 -1.170675 -0.918558 -1.224745
24 -1.264185  0.800654 -1.056944 -1.312977 -1.224745